pains_dev:
  adapter: mysql2
  database: pains
  host: mydatabase.cnagkwbcmmva.ap-northeast-1.rds.amazonaws.com
  username: takahide 
  password: taka0763
  encoding: utf8
local_dev:
  adapter: mysql2
  database: pains
  host: localhost
  username: root 
  password:
  encoding: utf8
